def get_scripts() -> str:
    return r'''
const steps=ir.steps||[], product=ir.product||{}, bom=ir.bill_of_materials||[];
const STORAGE_KEY='minimalWizard:'+ (product.name||'product');
let currentStep=0, grades={}, started=false;
function esc(v){return String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function load(){try{const s=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');currentStep=Math.min(Math.max(s.currentStep||0,0),Math.max(steps.length-1,0));grades=s.grades||{};started=!!s.started}catch(e){}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify({currentStep,grades,started}))}
function fmtWeight(p){return p?.weight!=null?`${p.weight} ${p.weight_unit||''}`.trim():'—'}
function materialName(v){const map={'1':'Plastic (ABS)','2':'Metal / Aluminium','3':'Glass','4':'Silicone / Rubber','5':'Copper','6':'Plastic + Metal','7':'Electronic','8':'Ceramic','9':'Metal / Copper'};return map[String(v)]||v||'Unknown'}
function init(){load();started=false;document.getElementById('productNameSide').textContent='Disassembly Wizard';document.getElementById('productSubtitle').textContent=product.name||'';renderWelcome();renderSidebar();renderOverview();showWelcome()}

function renderWelcome(){
  document.getElementById('welcomeTitle').textContent=product.name||'Disassembly Wizard';
  document.getElementById('welcomeSteps').textContent=steps.length;
  document.getElementById('welcomeComponents').textContent=bom.length;
  document.getElementById('welcomeWeight').textContent=fmtWeight(product);
  const p=product.image?.path;
  document.getElementById('welcomeImage').innerHTML=p?`<img src="${esc(p)}" alt="${esc(product.name||'Product')}" onclick="openImage('${esc(p)}')">`:'<div class="welcome-placeholder">No product image available</div>';
}
function showWelcome(){document.body.classList.add('welcome-mode');document.getElementById('welcomeView').classList.remove('hidden');document.getElementById('stepView').classList.add('hidden');document.getElementById('summaryView').classList.add('hidden')}
function showStepView(scroll=true){document.body.classList.remove('welcome-mode');document.getElementById('welcomeView').classList.add('hidden');document.getElementById('summaryView').classList.add('hidden');document.getElementById('stepView').classList.remove('hidden');renderStep();renderSidebar();if(scroll)window.scrollTo({top:0,behavior:'smooth'})}
function startWizard(){started=true;currentStep=0;save();showStepView(true)}

function renderSidebar(){const box=document.getElementById('stepsList');box.innerHTML='';steps.forEach((s,i)=>{const b=document.createElement('button');b.className='step-item'+(i===currentStep?' active':'')+(i<currentStep?' completed':'');b.innerHTML=`<span class="step-num">${i<currentStep?'✓':i+1}</span><span class="step-copy"><strong>${esc(s.operation)}</strong><small>${(s.outputs||[]).length} outputs · ${(s.actions||[]).length} action${(s.actions||[]).length===1?'':'s'}</small></span>`;b.onclick=()=>goToStep(i);box.appendChild(b)})}
function goToStep(i){started=true;document.getElementById('welcomeView').classList.add('hidden');document.body.classList.remove('welcome-mode');document.getElementById('summaryView').classList.add('hidden');document.getElementById('stepView').classList.remove('hidden');currentStep=i;renderStep();renderSidebar();save();window.scrollTo({top:0,behavior:'smooth'})}
function renderStep(){if(!steps.length)return;const s=steps[currentStep];document.getElementById('stepCounter').textContent=`STEP ${currentStep+1} OF ${steps.length}`;document.getElementById('stepOperation').textContent=s.operation;document.getElementById('progressBar').style.width=`${(currentStep+1)/steps.length*100}%`;renderTools(s);renderImage(s);renderActions(s.actions||[]);renderContinues(s.continues_as);renderOutputs(s.outputs||[]);document.getElementById('prevBtn').disabled=currentStep===0;const next=document.getElementById('nextBtn');next.disabled=false;next.textContent=currentStep===steps.length-1?'Finish & view summary →':'Next →'}
function renderTools(s){let tools=s.tools_required||[];if(!tools.length)tools=(s.actions||[]).flatMap(a=>a.tools||[]);tools=[...new Set(tools.map(t=>typeof t==='string'?t:t?.name).filter(Boolean))];document.getElementById('toolsBox').innerHTML=tools.length?tools.map(t=>`<span class="tool-chip">🛠 ${esc(t)}</span>`).join(''):'<span class="tool-chip">No tools required (remove by hand)</span>'}
function firstImage(s){for(const a of s.actions||[])if(a.image?.path)return a.image.path;for(const o of s.outputs||[])if(o.image?.path)return o.image.path;return s.continues_as?.image?.path||product.image?.path||null}
function renderImage(s){const p=firstImage(s);document.getElementById('imageBox').innerHTML=p?`<img class="main-image" src="${esc(p)}" alt="${esc(s.operation)}" onclick="openImage('${esc(p)}')">`:'<div class="image-placeholder">No image available</div>'}
function renderActions(actions){const box=document.getElementById('actionsList');box.innerHTML=(actions.length?actions:[{text:steps[currentStep].operation}]).map((a,i)=>`<div class="instruction"><span class="instruction-num">${i+1}</span><p>${esc(a.text)}</p></div>`).join('')}
function renderContinues(c){document.getElementById('continuesAs').innerHTML=c?`<div class="continues">↳ Remaining assembly after this step: <strong>${esc(c.name)}</strong></div>`:'<div class="continues">This is the final disassembly step.</div>'}
function stateKey(p,i){return String(p.node_id??i)}
function renderOutputs(outputs){const box=document.getElementById('outputsList');if(!outputs.length){box.innerHTML='<div class="continues">No parts removed in this step.</div>';return}box.innerHTML=outputs.map((p,i)=>{const k=stateKey(p,i),st=grades[k]||{};const img=p.image?.path?`<img class="part-img" src="${esc(p.image.path)}" alt="${esc(p.name)}" onclick="openImage('${esc(p.image.path)}')">`:'<div class="part-img image-placeholder">No image</div>';return `<article class="part-card">${img}<div class="part-body"><h4>${esc(p.name)}</h4><div class="meta">Weight: <strong>${fmtWeight(p)}</strong><br>Material: <strong>${esc(materialName(p.material))}</strong></div><div class="grade-row"><div class="field"><label>Quality</label><select onchange="updatePart('${k}','quality',this.value)"><option value="">— not graded —</option><option ${st.quality==='Excellent'?'selected':''}>Excellent</option><option ${st.quality==='Working'?'selected':''}>Working</option><option ${st.quality==='Damaged'?'selected':''}>Damaged</option><option ${st.quality==='Scrap'?'selected':''}>Scrap</option></select></div><div class="field"><label>Measured</label><input type="number" min="0" step="0.1" value="${esc(st.measured??'')}" placeholder="meas. g" oninput="updatePart('${k}','measured',this.value)"></div></div></div></article>`}).join('')}
function updatePart(k,f,v){grades[k]=grades[k]||{};grades[k][f]=v;save()}
function nextStep(){if(currentStep<steps.length-1)goToStep(currentStep+1);else showSummary()}
function previousStep(){if(currentStep>0)goToStep(currentStep-1)}
function openImage(p){document.getElementById('modalImage').src=p;document.getElementById('imageModal').classList.add('show')}
function closeImage(){document.getElementById('imageModal').classList.remove('show')}
function renderOverview(){document.getElementById('overviewContent').innerHTML=`<div class="overview-grid"><div class="overview-card"><span>Product</span><strong>${esc(product.name||'—')}</strong></div><div class="overview-card"><span>Total steps</span><strong>${steps.length}</strong></div><div class="overview-card"><span>BOM items</span><strong>${bom.length}</strong></div><div class="overview-card"><span>Weight</span><strong>${fmtWeight(product)}</strong></div><div class="overview-card"><span>Depth</span><strong>${esc(ir.depth?.mode||'full')}</strong></div><div class="overview-card"><span>Schema</span><strong>${esc(ir.schema_version||'—')}</strong></div></div>`}
function showOverview(){document.getElementById('overviewPanel').classList.remove('hidden')}
function hideOverview(){document.getElementById('overviewPanel').classList.add('hidden')}
function destinationFor(q){if(q==='Excellent')return {label:'Reuse / resell',cls:'dest-reuse'};if(q==='Working')return {label:'Repair & resell',cls:'dest-repair'};if(q==='Damaged')return {label:'Repair / recycle',cls:'dest-damaged'};if(q==='Scrap')return {label:'Recycle',cls:'dest-scrap'};return {label:'—',cls:''}}
function gradeClass(q){return q?`grade-${q.toLowerCase()}`:'grade-none'}
function showSummary(){save();document.getElementById('stepView').classList.add('hidden');document.getElementById('summaryView').classList.remove('hidden');renderSummary();window.scrollTo({top:0,behavior:'smooth'})}
function renderSummary(){const counts={Excellent:0,Working:0,Damaged:0,Scrap:0,ungraded:0};bom.forEach((p,i)=>{const q=(grades[stateKey(p,i)]||{}).quality||'';if(q)counts[q]++;else counts.ungraded++});const graded=bom.length-counts.ungraded;document.getElementById('summarySubtitle').textContent=`${product.name||'Product'} · ${graded} of ${bom.length} components graded`;document.getElementById('summaryStats').innerHTML=`<div><span>Total components</span><strong>${bom.length}</strong></div><div><span>Excellent</span><strong>${counts.Excellent}</strong></div><div><span>Working</span><strong>${counts.Working}</strong></div><div><span>Damaged</span><strong>${counts.Damaged}</strong></div><div><span>Scrap</span><strong>${counts.Scrap}</strong></div>`;document.getElementById('summaryWarning').innerHTML=counts.ungraded?`<div class="summary-warning">⚠ ${counts.ungraded} component${counts.ungraded===1?' is':'s are'} not graded yet.</div>`:'<div class="summary-success">✓ All recovered components have been graded.</div>';document.getElementById('summaryRows').innerHTML=bom.map((p,i)=>{const st=grades[stateKey(p,i)]||{},q=st.quality||'',dest=destinationFor(q),img=p.image?.path?`<img src="${esc(p.image.path)}" alt="${esc(p.name)}">`:'<span class="table-no-image">—</span>';return `<tr><td class="summary-thumb">${img}</td><td><strong>${esc(p.name)}</strong></td><td>${esc(materialName(p.material))}</td><td>${fmtWeight(p)}</td><td>${st.measured!==undefined&&st.measured!==''?esc(st.measured)+' '+esc(p.weight_unit||'g'):'—'}</td><td><span class="grade-badge ${gradeClass(q)}">${esc(q||'not graded')}</span></td><td><span class="destination ${dest.cls}">${esc(dest.label)}</span></td></tr>`}).join('')}
function backToSteps(){document.getElementById('summaryView').classList.add('hidden');document.getElementById('stepView').classList.remove('hidden');renderStep();window.scrollTo({top:0,behavior:'smooth'})}
function restartWizard(){if(!confirm('Restart the wizard and clear all grades and measured weights?'))return;localStorage.removeItem(STORAGE_KEY);grades={};currentStep=0;started=false;renderSidebar();showWelcome();window.scrollTo({top:0,behavior:'smooth'})}
document.addEventListener('keydown',e=>{if(e.key==='ArrowRight'&&!document.getElementById('stepView').classList.contains('hidden'))nextStep();if(e.key==='ArrowLeft'&&!document.getElementById('stepView').classList.contains('hidden'))previousStep();if(e.key==='Escape'){closeImage();hideOverview()}});init();
'''
